### ISSUE TITLE
volunteers - automated email reminders for shifts that they signed up for or that are open?

### ISSUE THREAD

**Issue by jstelnik** [MathForABetterWorld/MathForABetterWorld#118]

**Comment by jstelnik** [comment]
can maybe be done on aws

**Comment by ChrisWilhelm** [comment]
> can maybe be done on aws

Using AWS SNS (simple notification system)

**Comment by ChrisWilhelm** [comment]
https://aws.amazon.com/blogs/contact-center/automate-appointment-reminders-using-amazon-pinpoint-and-amazon-connect/

**Comment by jstelnik** [comment]
or nodemailer
