### ISSUE TITLE
Optional expiration date issue

### ISSUE THREAD

**Issue by sofialovuolo** [MathForABetterWorld/MathForABetterWorld#180]
Again on the volunteer page import form the expiration date field says its optional and it should be optional but it defaults to 1970 and it  will not let the user leave the box empty

**Comment by jstelnik** [comment]
this is what it is supposed to be

**Comment by sofialovuolo** [comment]
is it optional or not? because it says optional in the heading but then it isn't optional when submitting

**Comment by jstelnik** [comment]
Ok I will look at it. I'll see if it can just default to empty. I know it's optional on the backend but might not be on the frontend

**Comment by jstelnik** [comment]
if the date is in 1970, there is no expiration date. no way to change it besides this. so when it says 1970, it's 'empty'
